# Generated by Django 3.1.4 on 2021-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210126_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
