# Generated by Django 3.1.4 on 2021-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.CharField(blank=True, default='https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885_1280.jpg', max_length=800, null=True),
        ),
    ]
